# -*- coding: utf-8 -*-
"""mcl-legal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLSW_dQnuYfa_79X6qV_pcYxG38_cgLa
"""
import mcl_utils as mclu
import re

def extract_from_legal(filepath):
  filetext = mclu.extract_text(filepath, endpg=4)
  companies = mclu.get_answer(filetext, "name of the companies in the joint venture")
  companies = re.findall(r'"([^"]*)"', companies)
  
  for i in range(len(companies)):
      companies[i] = companies[i].replace("$", "").strip()
      
  partnership = {}
  lead = companies[0]
  for c in companies:
    share = mclu.get_answer(filetext, "partnership share of " + c + " in the joint venture/consortium")
    share = int(re.findall(r"([0-9]+)[ ]*[%]", share)[0])/100
    partnership[c] = share
  for c in companies:
      if partnership[lead] < partnership[c]:
          lead = c
  return partnership, lead

info = extract_from_legal("D:\\CV\\Project\\MCL\\Govind Files\\lab system\\mcl\\MCL data\\GODAWARI DEIFY SCMPL JV\\5_Legal_Status_of_the_bidder.pdf")
print(info)